apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: joohong89/assessment-order-task2
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: CONNECTION_STRING
          value: "mongodb://db-mongo:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: order
  annotations:
   konghq.com/plugins: rate-limiting
spec:
  type: NodePort
  selector:
    app: order
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31788
  
